### ISSUE TITLE
No typ attribute in security header when generating JWT with encode_jwt

### ISSUE THREAD

**Issue by loic-prieto** [DCIT/perl-Crypt-JWT#10]
Hi!

I've been using the library for some weeks, and I just noticed that when using the encode_jwt function with an RSA key to create a token, the Header is just { "alg":"PS512" } (obviously, I'm using the PS512 alg). But the typ attribute does not exist.

Is this a valid JWT token? I thought a valid JWT should have a typ attribute in the Header (albeit, always of value JWT).

**Comment by karel-m** [comment]
According to https://tools.ietf.org/html/rfc7519#section-5.1 "Use of this Header Parameter is OPTIONAL"

**Comment by loic-prieto** [comment]
Indeed it is, my bad here.

Thanks!
