### ISSUE TITLE
JWS token is getting encrypted?

### ISSUE THREAD

**Issue by foobargeez** [DCIT/perl-Crypt-JWT#15]
Hello,
I am looking to just sign a token using Crypt::JWT but I don't see a difference between JWS and JWE tokens.  See the below:

```
#! /usr/local/bin/perl

use Crypt::JWT qw(encode_jwt decode_jwt);

my $jws_token = encode_jwt(payload => "haha", alg => "HS256", key => 'secret');
my $jwe_token = encode_jwt(payload => "haha", alg => "HS256", enc => 'A128GCM', key => 'secret');

my $data1 = decode_jwt(token=>$jws_token, key=>'secret');

print "-->$jws_token--$jwe_token--$data1<--\n";
```

Am I missing something obvious?

Thanks in advance!

**Comment by karel-m** [comment]
The combination `alg => "HS256"` + `enc => "A128GCM"` is not correct.

Try:
```perl
use Crypt::JWT qw(encode_jwt decode_jwt);

my $jws_token = encode_jwt(payload => "ha1", alg => "HS256", key => 'secret');
my $jwe_token = encode_jwt(payload => "ha2", alg => "PBES2-HS512+A256KW", enc => 'A128GCM', key => 'secret');

my $data1 = decode_jwt(token=>$jws_token, key=>'secret');
my $data2 = decode_jwt(token=>$jwe_token, key=>'secret');

print "JWS:$jws_token\n";
print "OUT:$data1\n";
print "JWE:$jwe_token\n";
print "OUT:$data2\n";
```

**Comment by foobargeez** [comment]
Thanks.  I guess the part I am confused about is, why isn't the JWS token in clear text?  I tried reading the payload by pasting in say, https://jwt.io.  My understanding is that the payload should still be in clear text and the difference between JWS and JWT is that the former is additionally signed.  Do I make sense? :-)

**Comment by karel-m** [comment]
JWS payload as well JWS header are just base64 encoded.

Let's have a JWS:
```
eyJhbGciOiJIUzI1NiJ9.aGEx.9KYaQYJ-alFIe0vTQ2lrw5LsZTOf7Oean-eA6TP3AeM
<------header------>.<-->.<----------------signature---------------->


$ echo eyJhbGciOiJIUzI1NiJ9 | base64 -d
{"alg":"HS256"}

$ echo aGEx | base64 -d
ha1
```

On the other hand JWT is truly encrypted.

**Comment by foobargeez** [comment]
Great, thanks!  Thanks for the awesome module!
