### ISSUE TITLE
verify_xxx options do not work with decode_payload=0

### ISSUE THREAD

**Issue by mnz2000** [DCIT/perl-Crypt-JWT#31]
This is kind of obvious when one thinks about it, but I didn't. Spent some time wondering why verify_aud didn't work. I could imagine someone not testing for verify_xxx failures and thinking everything works when verification in fact doesn't happen at all.

Possible fixes:

1. Croak if verify_xxx options are specified with decode_payload=0.

2. Add a mention about it in the POD under decode_payload.

**Comment by karel-m** [comment]
Could you please check the patch above?

**Comment by mnz2000** [comment]
Looks good to me.
