### ISSUE TITLE
doesn't handle errors...

### ISSUE THREAD

**Issue by knutesears** [DCIT/perl-Crypt-JWT#34]
I was very surprised to find out that there seems to be no error handling.  I passed a malformed JWT with a bad signature to the decode_jwt method and it simply crashed the perl script.  Why not have it at least return a 0 or something?  Am I now supposed to put it in an eval, or use a try-catch module?  Think I'll go hunt for a different JWT module instead.

**Comment by karel-m** [comment]
Yes, is intended to be put into eval.

Simply returning 0 on error does not allow to pass the information about error detail/reason.

I am sorry, this is not going to change.
