### ISSUE TITLE
Warning messages when using Crypt-JWT and JSON modules

### ISSUE THREAD

**Issue by smutel** [DCIT/perl-Crypt-JWT#8]
Hello,

When I import the two perl modules below:

use JSON;
use Crypt::JWT qw(encode_jwt);

Warning messages below are displayed:

Subroutine JSON::XS::Boolean::("" redefined at /usr/share/perl5/overload.pm line 23.
Subroutine JSON::XS::Boolean::(eq redefined at /usr/share/perl5/overload.pm line 23.

Regards.

**Comment by karel-m** [comment]
I guess that you have a bit old `Cpanel::JSON::XS` that is affected by this https://github.com/rurban/Cpanel-JSON-XS/issues/60

Try to upgrade to the latest `Cpanel::JSON::XS`

**Comment by karel-m** [comment]
ping @smutel

**Comment by smutel** [comment]
Hello,

I am not able to update Cpanel::JSON::XS on my current system.
So for the moment I don't display warning errors in my script.

Thanks.

**Comment by karel-m** [comment]
OK, could you please confirm, that you have `Cpanel::JSON::XS` versoin `<3.0213` ?

If so, I would close this issue as it is sort of a "known bug" in `Cpanel::JSON::XS`

**Comment by smutel** [comment]
Yes, I have version 3.0104.

2017-01-16 14:44 GMT+01:00 karel-m <notifications@github.com>:

**Comment by karel-m** [comment]
Great (well, I know, not so great for you). So I am closing this issue. Feel free to open a new one if you have troubles after `Cpanel::JSON::XS` upgrade.

**Comment by mrdvt92** [comment]
I had this same issue on stock el6 and I used JSON::PP to get around the issue.
